

github_token     = "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"
github_repo_owner = "fictionalizecommandmentsilently"
github_repo_name = "duchenne"
github_branch    = "main"
